"""
Traffic light program definitions — only depends on traci.
Isolated here so it can be imported by both dashboard.py and sumo_env.py
without pulling in gymnasium or numpy.
"""

import traci


def apply_tl_programs():
    """
    TL_A and TL_B are complex 5-arm intersections — their default SUMO programs
    (generated by netconvert) are conflict-free and must not be replaced.
    The PPO agent controls them by directly calling setPhase() via TraCI,
    so the underlying program only needs to have phases 0 and 4 available,
    which the netconvert-generated programs do.

    TL_C is a T-junction with full approach conflicts that netconvert cannot
    resolve automatically, so we apply a strict one-approach-at-a-time program.
    """
    # ── TL_C: T-junction needs strict one-approach-at-a-time program ────────
    tl_id = "6073919354_C"
    try:
        #            link:  0  1  2  3  4  5
        phases = [
            traci.trafficlight.Phase(41, "GGrrrr"),  # approach A open
            traci.trafficlight.Phase(4,  "yyrrrr"),  # yellow A
            traci.trafficlight.Phase(41, "rrGGrr"),  # approach B open
            traci.trafficlight.Phase(4,  "rryyrr"),  # yellow B
            traci.trafficlight.Phase(41, "rrrrGG"),  # approach C (E0) open
            traci.trafficlight.Phase(4,  "rrrryy"),  # yellow C
        ]
        logic = traci.trafficlight.Logic("tjunc_3phase", 0, 0, phases)
        traci.trafficlight.setProgramLogic(tl_id, logic)
        traci.trafficlight.setProgram(tl_id, "tjunc_3phase")
        print(f"[TL CONFIG] {tl_id}: 3-phase conflict-free program applied")
    except Exception as e:
        print(f"[TL CONFIG] Failed to apply {tl_id} program: {e}")
